### PR TITLE
feat: new state CANCELLATION_EXPIRED

### PR DESCRIPTION
**Pull request by pietro-tota**
SonarCloud outcome analysis can be see [here](https://sonarcloud.io/component_measures?metric=new_coverage&selected=pagopa_pagopa-ecommerce-commons%3Asrc%2Fmain%2Fjava%2Fit%2Fpagopa%2Fecommerce%2Fcommons%2Fdomain%2Fv1%2FTransactionWithClosureError.java&view=list&branch=refs%2Fpull%2F49%2Fmerge&id=pagopa_pagopa-ecommerce-commons)
Since this PR does not target main branch SonarCloud analysis was performed manually triggering [code review pipeline](https://dev.azure.com/pagopaspa/pagoPA-projects/_build/results?buildId=78534&view=results) 
#### List of Changes

Add new state CANCELLATION_EXPIRED.
This state is reached when a transaction cancellation is requested by the user.
In this case transactions-service will invoke Nodo closePayment KO to effectively unlock the debt position.
So in a happy path flow the transaction will flow as below:
`ACTIVATED` -> `CANCELLATION_REQUESTED` -> `CANCELED`.
In an error occurs during closePayment KO process then the flow will be:
`ACTIVATED` -> `CANCELLATION_REQUESTED` -> `CLOSURE_ERROR`-> `CANCELED`.
If the transaction is stuck in CANCELLATION_REQUESTED or CLOSURE_ERROR statuses then, after expiration, it will go to CANCELLATION_EXPIRED new state.

#### Motivation and Context

This modification is needed in order to distinguish the expiration of a transaction from the one for which an authorization was requested (and then needs a refund to be process) and a transaction that has not requested an authorization yet (for which no refund is needed since no authorization was requested at all).

#### How Has This Been Tested?
Junit tests

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by MarcoAGreco — APPROVED** [review]
🚀

**Comment by infantesimone** [comment]
I'm not sure if this status is useful, when the transaction goes into the `expired` it is decided based on whether there is an authorization requested to perform the refund, without using another status, or is there some other case?

**Comment by pietro-tota** [comment]
> I'm not sure if this status is useful, when the transaction goes into the `expired` it is decided based on whether there is an authorization requested to perform the refund, without using another status, or is there some other case?

Yes, but without this state the transaction will then remain in CANCELLATION_REQUESTED state? 
This will lead to the fact that CANCELLATION_REQUESTED state can be seen both as final and non-final.
The approach here is the same used for the state `EXPIRED_NOT_AUTHORIZED`

**Comment by infantesimone** [comment]
> > I'm not sure if this status is useful, when the transaction goes into the `expired` it is decided based on whether there is an authorization requested to perform the refund, without using another status, or is there some other case?
> 
> Yes, but without this state the transaction will then remain in CANCELLATION_REQUESTED state? This will lead to the fact that CANCELLATION_REQUESTED state can be seen both as final and non-final. The approach here is the same used for the state `EXPIRED_NOT_AUTHORIZED`

you convinced me :-)

**Review by infantesimone — APPROVED** [review]

**Pull request merged**
