### PR TITLE
feat: move events to v1 subpackage

### PR DESCRIPTION
**Pull request by pietro-tota**
#### List of Changes
Move all new refactored events, domains and pojo to v1 subpackage 

#### Motivation and Context
This modification will prevent further dependent modules refactoring for event versioning modifications

#### How Has This Been Tested?
Local junit tests

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by giovanniberti** [comment]
I think we should move domain objects and pojos to a `v1` package, as these depend directly on event data which is versioned

**Comment by pietro-tota** [comment]
> I think we should move domain objects and pojos to a `v1` package, as these depend directly on event data which is versioned

Yes, you're absolutely right, done!

**Comment by giovanniberti** [comment]
Could you mirror the versioning in test packages too? :)

**Comment by pietro-tota** [comment]
> Could you mirror the versioning in test packages too? :)

Done :)

**Review by giovanniberti — APPROVED** [review]
🏅

**Pull request merged**
