### PR TITLE
[CHK-912] feat(confidential): add new mode for AES cipher with no salt and deterministic IV

### PR DESCRIPTION
**Pull request by giovanniberti**
#### List of Changes

* allow AES cipher to optionally not use salt
* add new `ConfidentialDataManager.Mode` with deterministic IV and no salt

#### Motivation and Context

This PR builds on top of #34 to support specific use-cases were salting would be detrimental (e.g. search by encrypted email address).
The implementation introduces a new protection `Mode` called `AES_GCM_NOPAD_NOSALT_DETERMINISTIC_IV`. As the name implies, this mode doesn't use salting and computes a deterministic IV instead of a cryptographically secure nonce.
This is done in order to have the same ciphertext given the same plaintext, in the case of email addresses this would directly allow search without decryption.
The deterministic IV currently is computed as the first 12 bytes of the SHA-1 hash of the plaintext data.

#### How Has This Been Tested?

Local unit tests

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

Depends on #34

### CODE REVIEW

**Review by pietro-tota — APPROVED** [review]
Great🚀 Fix just some code smells. Well done!

**Review by pietro-tota — APPROVED** [review]
🚀

**Review by infantesimone — APPROVED** [review]

**Comment by giovanniberti** [comment]
Closed as nonce reuse in GCM is [catastrophic](https://crypto.stackexchange.com/questions/26790/how-bad-it-is-using-the-same-iv-twice-with-aes-gcm)

**Comment by giovanniberti** [comment]
Closed as nonce reuse in GCM is [catastrophic](https://crypto.stackexchange.com/questions/26790/how-bad-it-is-using-the-same-iv-twice-with-aes-gcm)

**Pull request closed without merging**
